# Generated by Django 5.0.3 on 2024-04-23 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Budget_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type_name', models.CharField(default='Non-independent house', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(default='Single Room', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=10, null=True)),
                ('house_name', models.CharField(max_length=20, null=True)),
                ('owner_name', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_home.area')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_home.property_type')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnished', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('lat_bath', models.CharField(max_length=20)),
                ('rent', models.IntegerField()),
                ('electricity_bill_per_unit', models.IntegerField(blank=True, null=True)),
                ('room_for', models.CharField(default='For Boys', max_length=10)),
                ('deposite_money', models.IntegerField(default=1000)),
                ('budget_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_home.budget_range')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_home.house')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_home.roomtype')),
            ],
        ),
    ]
