# Generated by Django 5.0.3 on 2024-03-17 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_no", models.CharField(max_length=10, null=True)),
                ("house_name", models.CharField(max_length=20, null=True)),
                ("owner_name", models.CharField(max_length=30)),
                ("contact_no", models.IntegerField(max_length=12)),
                ("address", models.TextField()),
                ("area_belong", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bhk", models.IntegerField(null=True)),
                ("available", models.BooleanField()),
                ("balcony", models.BooleanField()),
                ("lat_bath", models.TextField(max_length=20)),
                ("rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("electricity", models.TextField(max_length=15)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rent_home.house",
                    ),
                ),
                (
                    "room_type",
                    models.ManyToManyField(related_name="houses", to="rent_home.type"),
                ),
            ],
        ),
    ]
