# Generated by Django 5.0.3 on 2024-03-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_home", "0002_remove_roomtype_room_type_house_room_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="room_type",
            field=models.ManyToManyField(related_name="house", to="rent_home.type"),
        ),
    ]
