# Generated by Django 5.0.3 on 2024-03-29 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_home", "0003_roomtype_room_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="house", name="room_types",),
        migrations.RemoveField(model_name="roomtype", name="room_type",),
        migrations.RemoveField(model_name="roomtype", name="available",),
        migrations.RemoveField(model_name="roomtype", name="balcony",),
        migrations.RemoveField(model_name="roomtype", name="bhk",),
        migrations.RemoveField(model_name="roomtype", name="electricity",),
        migrations.RemoveField(model_name="roomtype", name="house",),
        migrations.RemoveField(model_name="roomtype", name="lat_bath",),
        migrations.RemoveField(model_name="roomtype", name="rent",),
        migrations.AddField(
            model_name="roomtype",
            name="room_type_name",
            field=models.CharField(default="Single Room", max_length=50),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bhk", models.IntegerField(null=True)),
                ("available", models.BooleanField(default=False)),
                ("balcony", models.BooleanField()),
                ("lat_bath", models.TextField(max_length=20)),
                ("rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("electricity", models.TextField(max_length=15)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rent_home.house",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rent_home.roomtype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Type",),
    ]
