# Generated by Django 5.0.3 on 2024-04-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rent_home",
            "0004_remove_house_room_types_remove_roomtype_room_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Budget_Range",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_range", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Property_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type_name",
                    models.CharField(default="Non-independent house", max_length=50),
                ),
            ],
        ),
        migrations.RemoveField(model_name="house", name="area_belong",),
        migrations.RemoveField(model_name="room", name="room_type",),
        migrations.AddField(
            model_name="room",
            name="furnished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room", name="balcony", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="bhk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rent_home.roomtype"
            ),
        ),
        migrations.AlterField(
            model_name="room", name="rent", field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="house",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rent_home.area",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="budget_range",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rent_home.budget_range",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="property_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rent_home.property_type",
            ),
        ),
    ]
