# Generated by Django 5.0.3 on 2024-04-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_home", "0005_area_budget_range_property_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="bhk",),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rent_home.roomtype",
            ),
        ),
    ]
