# Generated by Django 5.0.3 on 2024-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_home", "0006_remove_room_bhk_room_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="deposite_money",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="room", name="latitude", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="room", name="longitude", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="room_for",
            field=models.TextField(default="For Boys", max_length=10),
        ),
    ]
