# Generated by Django 5.0.3 on 2024-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_home", "0007_room_deposite_money_room_latitude_room_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="latitude",),
        migrations.RemoveField(model_name="room", name="longitude",),
        migrations.AddField(
            model_name="house", name="latitude", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="house", name="longitude", field=models.FloatField(null=True),
        ),
    ]
